AWSTemplateFormatVersion: 2010-09-09
Description: |
  Allows Services to content to RDS
Parameters:
  Environment:
    Type: String
    Description: Environment to Deploy
    Default: dev

Resources:
  WpRdsDBServerAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${Environment}-Vpc
      GroupDescription: Instances with access to WP RDS server
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${Environment}-RDSAccess
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

Outputs:
  WpRdsDBServerAccessSecurityGroup:
    Description: VPC specific security group for WP RDS server
    Value: !Ref WpRdsDBServerAccessSecurityGroup
    Export:
      Name: !Sub ${Environment}-WpRdsDBServerAccessSecurityGroup