locals {
  python = (substr(pathexpand("~"), 0, 1) == "/") ? "python3" : "python.exe"
}
resource "null_resource" "this" {
  triggers = {
    always_run = timestamp()
  }
  provisioner "local-exec" {
    command     = "${local.python} -u ${path.module}/scripts/run.py --template_yaml_dir ${var.template_yaml_dir} --template_input_file_name ${var.template_input_file_name} --template_output_file_name ${var.template_output_file_name} --app_role ${var.app_role} --envoutput ${var.env_output_file_location} --parameter_override_file_name ${var.parameter_override_file_name} --envvars ${join(" ", var.env_variables)} --ignore_patterns ${join(" ", var.ignore_patterns)} ${var.code_dir != null ? "--code_dir ${var.code_dir}" : ""} ${var.codebuild_project_name != null ? "--codebuild_project_name ${var.codebuild_project_name}" : ""} ${var.use_autogenerated_dot_env != null ? "--use_autogenerated_dot_env ${var.use_autogenerated_dot_env}" : ""} ${var.use_autogenerated_parameters != null ? "--use_autogenerated_parameters ${var.use_autogenerated_parameters}" : ""} ${var.pre_package_sh_location != null ? "--pre_package_sh_location ${var.pre_package_sh_location}" : ""} ${var.post_package_sh_location != null ? "--post_package_sh_location ${var.post_package_sh_location}" : ""} ${var.pre_deploy_sh_location != null ? "--pre_deploy_sh_location ${var.pre_deploy_sh_location}" : ""} ${var.post_deploy_sh_location != null ? "--post_deploy_sh_location ${var.post_deploy_sh_location}" : ""} ${var.bucket_name_pattern != null ? "--bucket_name_pattern '${var.bucket_name_pattern}'" : ""} ${var.dir_to_sync != null ? "--dir_to_sync ${var.dir_to_sync}" : ""} --ci_only ${var.ci_only} --use_pipeline_application_role ${var.use_pipeline_application_role}"
    on_failure  = fail
    interpreter = ["/bin/bash", "-c"]
  }
  lifecycle {
    create_before_destroy = true
  }
}
