variable "code_dir" {
  type        = string
  description = "Project root dir"
  default     = null
}
variable "template_yaml_dir" {
  type        = string
  description = "serverless yaml dir location"
}

variable "template_input_file_name" {
  type        = string
  description = "CloudFormation/SAM template input file name"
}
variable "template_output_file_name" {
  type        = string
  description = "CloudFormation/SAM template output file name"
  default     = "rendered_template.yml"
}

variable "parameter_override_file_name" {
  type        = string
  description = "Parameter Override File Name"
  default     = "parameters.json"
}
variable "app_role" {
  type        = string
  description = "Application Role"
}
variable "env_output_file_location" {
  type        = string
  description = "Output for .env file location"
}
variable "env_variables" {
  type        = list(string)
  description = "List of environment variables that has to be outputed to env_file_location"
}
variable "ignore_patterns" {
  type        = list(string)
  description = "Folder ignore patterns that will be execluded from the artifact"
  default     = ["*.terraform", "*.git", "node_modules"]
}
variable "bucket_name_pattern" {
  type        = string
  default     = null
  description = "Bucket Name pattern to sync folder to s3"
}
variable "dir_to_sync" {
  type        = string
  default     = null
  description = "Local relative folder dir to sync to s3"
}
variable "pre_package_sh_location" {
  type        = string
  default     = null
  description = "Pre Package Script File location with executable permission"
}
variable "post_package_sh_location" {
  type        = string
  default     = null
  description = "Post Package Script File location with executable permission"
}
variable "pre_deploy_sh_location" {
  type        = string
  default     = null
  description = "Pre Deploy Script File location with executable permission"
}
variable "post_deploy_sh_location" {
  type        = string
  default     = null
  description = "Post Deploy Script File location with executable permission"
}
variable "use_autogenerated_dot_env" {
  type        = bool
  default     = true
  description = "Use autogenerated dot env file from pipeline"
}
variable "use_autogenerated_parameters" {
  type        = bool
  default     = true
  description = "Use autogenerated dot env file from pipeline (parameters.json) file will be used"
}
variable "codebuild_project_name" {
  type        = string
  default     = null
  description = "CodeBuild project name to retrieve env and parameters when deploying locally"
}
variable "ci_only" {
  type        = bool
  default     = false
  description = "Run Continuous Integration Only"
}
variable "use_pipeline_application_role" {
  type        = bool
  default     = false
  description = "Role to use when running deployment"
}
