AWSTemplateFormatVersion: 2010-09-09
Description: Enabling cloudtrail logs seperately as data and management events and store in S3 buckets for each accounts
Parameters: 
  OperatorEmail: 
    Description: "Email address to notify when new logs are published."
    Type: String
    Default: "devops@homeloanexperts.com.au"
  Environment:
    Type: String
    Description: "The environment to deploy to"
    Default: "dev"
Resources: 
  CloudtrailLoggingBucket: 
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${Environment}-cloudtrail-logging-${AWS::Region}'
  BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: CloudtrailLoggingBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: 
              !Sub |-
                arn:aws:s3:::${CloudtrailLoggingBucket}
          - 
            Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource:
              !Sub |-
                arn:aws:s3:::${CloudtrailLoggingBucket}/AWSLogs/${AWS::AccountId}/*
            Condition: 
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
  Topic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - 
          Endpoint: 
            Ref: OperatorEmail
          Protocol: email
  TopicPolicy: 
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - Ref: "Topic"
      PolicyDocument: 
        Version: "2008-10-17"
        Statement: 
          - 
            Sid: "AWSCloudTrailSNSPolicy"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Resource: "*"
            Action: "SNS:Publish"
  HLETrail: 
    DependsOn: 
      - BucketPolicy
      - TopicPolicy
    Type: AWS::CloudTrail::Trail
    Properties: 
      S3BucketName: 
        Ref: CloudtrailLoggingBucket
      SnsTopicName: 
        Fn::GetAtt: 
          - Topic
          - TopicName
      IsLogging: true
      IsMultiRegionTrail: false